# Generated by Django 5.2.3 on 2025-06-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок Блога', max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, help_text='Введите содержимое Блога', max_length=100, null=True, verbose_name='Содержимое')),
                ('png', models.ImageField(blank=True, help_text='Загрузите фото', null=True, upload_to='products/photo', verbose_name='Превью (изображение),')),
                ('creation_date', models.DateField(help_text='Дата создания', verbose_name='Дата создания')),
                ('publication', models.BooleanField(help_text='Да/Нет', verbose_name='Признак публикации')),
                ('views_counter', models.PositiveIntegerField(default=0, help_text='Укажите количество просмотров', verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
                'ordering': ['title', 'content', 'png', 'creation_date', 'publication'],
            },
        ),
    ]
