# Generated by Django 5.2.3 on 2025-07-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idiots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idiots',
            name='phone',
        ),
        migrations.AddField(
            model_name='idiots',
            name='country',
            field=models.CharField(blank=True, help_text='Страна', max_length=50, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='idiots',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Номер Телефона', max_length=35, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='idiots',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Аватар', null=True, upload_to='idiots/avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='idiots',
            name='tg_name',
            field=models.CharField(blank=True, help_text='Ник ТГ', max_length=35, null=True, verbose_name='Ник ТГ'),
        ),
    ]
