# Generated by Django 5.2.3 on 2025-06-21 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название продукта', max_length=100, verbose_name='Название')),
                ('description', models.CharField(blank=True, help_text='Введите описание продукта', max_length=100, null=True, verbose_name='Описание')),
                ('png', models.ImageField(blank=True, help_text='Загрузите фото', null=True, upload_to='product/photo', verbose_name='Фото')),
                ('price', models.CharField(help_text='Введите цену продукта', max_length=100, verbose_name='Цена')),
                ('created_at', models.CharField(help_text='Введите  продукта', max_length=100, verbose_name='Дата создания')),
                ('updated_at', models.CharField(help_text='Введите  продукта', max_length=100, verbose_name='Дата последнего изменения')),
                ('category', models.ForeignKey(blank=True, help_text='Введите категорию продукта', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Category', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name', 'price', 'created_at', 'updated_at'],
            },
        ),
    ]
