# Generated by Django 5.2.3 on 2025-06-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='png',
            field=models.ImageField(blank=True, help_text='Загрузите фото', null=True, upload_to='static/img', verbose_name='Фото'),
        ),
    ]
