# Generated by Django 5.2.3 on 2025-06-24 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views_counter',
            field=models.PositiveIntegerField(default=0, help_text='Укажите количество просмотров', verbose_name='Счетчик просмотров'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=None, help_text='Введите категорию продукта', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(auto_now_add=True, help_text='Введите  продукта', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='png',
            field=models.ImageField(blank=True, help_text='Загрузите фото', null=True, upload_to='products/photo', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateField(auto_now=True, help_text='Введите  продукта', verbose_name='Дата последнего изменения'),
        ),
    ]
